[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "cd frontend && serve -s build -l $PORT"

providers = ["node"]

[detectors]
node = "frontend"

[variables]
NODE_ENV = "production"
PUBLIC_URL = "."
