[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]
cmds = ["cd frontend && cp -r public/* /app/public/ 2>/dev/null || true"]

[phases.install]
cmds = ["cd frontend && npm install"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd frontend && serve -s build -l $PORT"

providers = ["node"]

[detectors]
node = "frontend"

[variables]
NODE_ENV = "production"
PUBLIC_URL = "."
